// Generated by `dart run live_activity_kit:setup` — do not edit.
// Source: package:live_activity_kit/ios/Shared/LANode.swift

import Foundation
import SwiftUI

/// The Swift mirror of the Dart component tree.
///
/// Decoding goes through `JSONSerialization` into `[String: Any]` rather than
/// `Codable`. A Live Activity re-renders on every content-state change — often
/// once a second — and a heterogeneous, deeply optional tree costs noticeably
/// more through `Decodable`'s keyed containers than through direct dictionary
/// lookups. Every field is optional and every failure is local: an unknown node
/// renders as nothing instead of failing the whole tree.

// MARK: - Node

public indirect enum LANode {
    case text(LATextNode)
    case image(LAImageNode)
    case row(LAStackNode)
    case column(LAStackNode)
    case progress(LAProgressNode)
    case circularProgress(LACircularProgressNode)
    case metric(LAMetricNode)
    case countdown(LACountdownNode)
    case spacer(LASpacerNode)
    case divider(LADividerNode)
    case padding(LAPaddingNode)
    case container(LAContainerNode)

    public static func parse(_ raw: Any?) -> LANode? {
        guard let json = raw as? [String: Any],
              let type = json["type"] as? String else { return nil }

        switch type {
        case "text": return .text(LATextNode(json))
        case "image": return .image(LAImageNode(json))
        case "row": return .row(LAStackNode(json, isRow: true))
        case "column": return .column(LAStackNode(json, isRow: false))
        case "progress": return .progress(LAProgressNode(json))
        case "circularProgress": return .circularProgress(LACircularProgressNode(json))
        case "metric": return .metric(LAMetricNode(json))
        case "countdown": return .countdown(LACountdownNode(json))
        case "spacer": return .spacer(LASpacerNode(json))
        case "divider": return .divider(LADividerNode(json))
        case "padding": return .padding(LAPaddingNode(json))
        case "container": return .container(LAContainerNode(json))
        default: return nil
        }
    }

    public static func parseAll(_ raw: Any?) -> [LANode] {
        (raw as? [Any])?.compactMap { LANode.parse($0) } ?? []
    }
}

// MARK: - Leaf nodes

public struct LATextNode {
    public let value: String
    public let size: CGFloat?
    public let weight: Font.Weight?
    public let color: Color?
    public let alignment: (TextAlignment, Alignment)?
    public let maxLines: Int?
    public let opacity: Double?
    public let italic: Bool
    public let monospacedDigit: Bool

    public init(_ json: [String: Any]) {
        let raw = (json["value"] as? String) ?? ""
        value = (json["uppercase"] as? Bool == true) ? raw.uppercased() : raw
        size = (json["size"] as? Double).map { CGFloat($0) }
        weight = LAFontWeight.parse(json["weight"])
        color = LAColor.parse(json["color"])
        alignment = LATextAlign.parse(json["align"])
        maxLines = (json["maxLines"] as? Double).map { Int($0) } ?? (json["maxLines"] as? Int)
        opacity = json["opacity"] as? Double
        italic = json["italic"] as? Bool == true
        monospacedDigit = json["mono"] as? Bool == true
    }
}

public struct LAImageNode {
    public enum Source: String {
        case systemName, asset, network, file
    }

    public let source: Source
    public let value: String
    public let size: CGFloat?
    public let width: CGFloat?
    public let height: CGFloat?
    public let color: Color?
    public let cornerRadius: CGFloat?

    public init(_ json: [String: Any]) {
        source = Source(rawValue: (json["source"] as? String) ?? "") ?? .systemName
        value = (json["value"] as? String) ?? ""
        size = (json["size"] as? Double).map { CGFloat($0) }
        width = (json["width"] as? Double).map { CGFloat($0) }
        height = (json["height"] as? Double).map { CGFloat($0) }
        color = LAColor.parse(json["color"])
        cornerRadius = (json["radius"] as? Double).map { CGFloat($0) }
    }
}

public struct LAStackNode {
    public let children: [LANode]
    public let spacing: CGFloat?
    public let align: LAAlign
    public let distribution: LADistribution

    /// `isRow` decides the cross-axis default, matching the Dart side:
    /// rows centre their children, columns lead them.
    public init(_ json: [String: Any], isRow: Bool = false) {
        children = LANode.parseAll(json["children"])
        spacing = (json["spacing"] as? Double).map { CGFloat($0) }
        align = LAAlign.parse(json["align"], default: isRow ? .center : .start)
        distribution = LADistribution.parse(json["distribution"])
    }
}

public struct LAProgressNode {
    public let value: Double
    public let tint: Color?
    public let track: Color?
    public let height: CGFloat
    public let cornerRadius: CGFloat?
    public let label: String?

    public init(_ json: [String: Any]) {
        value = min(max((json["value"] as? Double) ?? 0, 0), 1)
        tint = LAColor.parse(json["tint"])
        track = LAColor.parse(json["track"])
        height = CGFloat((json["height"] as? Double) ?? 6)
        cornerRadius = (json["radius"] as? Double).map { CGFloat($0) }
        label = json["label"] as? String
    }
}

public struct LACircularProgressNode {
    public let value: Double
    public let size: CGFloat
    public let lineWidth: CGFloat
    public let tint: Color?
    public let track: Color?
    public let center: LANode?

    public init(_ json: [String: Any]) {
        value = min(max((json["value"] as? Double) ?? 0, 0), 1)
        size = CGFloat((json["size"] as? Double) ?? 44)
        lineWidth = CGFloat((json["lineWidth"] as? Double) ?? 5)
        tint = LAColor.parse(json["tint"])
        track = LAColor.parse(json["track"])
        center = LANode.parse(json["center"])
    }
}

public struct LAMetricNode {
    public let value: String
    public let label: String?
    public let unit: String?
    public let symbol: String?
    public let align: LAAlign
    public let tint: Color?
    public let valueSize: CGFloat
    public let labelSize: CGFloat

    public init(_ json: [String: Any]) {
        value = (json["value"] as? String) ?? ""
        label = json["label"] as? String
        unit = json["unit"] as? String
        symbol = json["symbol"] as? String
        align = LAAlign.parse(json["align"], default: .start)
        tint = LAColor.parse(json["tint"])
        valueSize = CGFloat((json["valueSize"] as? Double) ?? 17)
        labelSize = CGFloat((json["labelSize"] as? Double) ?? 11)
    }
}

public struct LACountdownNode {
    public enum Style: String {
        case timer, relative, time, offset
    }

    public let date: Date
    public let style: Style
    public let size: CGFloat?
    public let weight: Font.Weight?
    public let color: Color?
    public let alignment: (TextAlignment, Alignment)?
    public let monospacedDigit: Bool
    public let prefix: String?
    public let suffix: String?

    public init(_ json: [String: Any]) {
        date = Date(timeIntervalSince1970: (json["until"] as? Double) ?? 0)
        style = Style(rawValue: (json["style"] as? String) ?? "") ?? .timer
        size = (json["size"] as? Double).map { CGFloat($0) }
        weight = LAFontWeight.parse(json["weight"])
        color = LAColor.parse(json["color"])
        alignment = LATextAlign.parse(json["align"])
        monospacedDigit = (json["mono"] as? Bool) ?? true
        prefix = json["prefix"] as? String
        suffix = json["suffix"] as? String
    }

    /// The SwiftUI date style that ticks without a payload update.
    ///
    /// `Text.DateStyle` is iOS 14+, while the pod itself deploys to 13.0 so it
    /// can be added to apps that predate Live Activities. Only the renderer
    /// (16.1+) ever reads this, so gating the property costs nothing.
    @available(iOS 14.0, *)
    public var textStyle: Text.DateStyle {
        switch style {
        case .timer: return .timer
        case .relative: return .relative
        case .time: return .time
        case .offset: return .offset
        }
    }
}

public struct LASpacerNode {
    public let minLength: CGFloat?

    public init(_ json: [String: Any]) {
        minLength = (json["minLength"] as? Double).map { CGFloat($0) }
    }
}

public struct LADividerNode {
    public let color: Color?
    public let thickness: CGFloat
    public let vertical: Bool

    public init(_ json: [String: Any]) {
        color = LAColor.parse(json["color"])
        thickness = CGFloat((json["thickness"] as? Double) ?? 0.5)
        vertical = json["vertical"] as? Bool == true
    }
}

public struct LAPaddingNode {
    public let insets: LAInsets
    public let child: LANode?

    public init(_ json: [String: Any]) {
        insets = LAInsets.parse(json["insets"]) ?? LAInsets()
        child = LANode.parse(json["child"])
    }
}

public struct LAContainerNode {
    public let child: LANode?
    public let background: Color?
    public let gradient: [Color]?
    public let cornerRadius: CGFloat?
    public let borderColor: Color?
    public let borderWidth: CGFloat?
    public let padding: LAInsets?
    public let width: CGFloat?
    public let height: CGFloat?
    public let align: LAAlign

    public init(_ json: [String: Any]) {
        child = LANode.parse(json["child"])
        background = LAColor.parse(json["background"])
        gradient = LAColor.parseAll(json["gradient"])
        cornerRadius = (json["radius"] as? Double).map { CGFloat($0) }
        borderColor = LAColor.parse(json["borderColor"])
        borderWidth = (json["borderWidth"] as? Double).map { CGFloat($0) }
        padding = LAInsets.parse(json["padding"])
        width = (json["width"] as? Double).map { CGFloat($0) }
        height = (json["height"] as? Double).map { CGFloat($0) }
        align = LAAlign.parse(json["align"], default: .center)
    }
}

// MARK: - Layout

/// One component tree per presentation region, plus theming.
public struct LALayout {
    public enum Region: String, CaseIterable {
        case compactLeading, compactTrailing, minimal
        case expandedLeading, expandedTrailing, expandedCenter, expandedBottom
        case lockScreen
    }

    public struct Theme {
        public let background: Color?
        public let gradient: [Color]?
        public let tint: Color?
        public let foreground: Color?

        public init(_ json: [String: Any]) {
            background = LAColor.parse(json["background"])
            gradient = LAColor.parseAll(json["gradient"])
            tint = LAColor.parse(json["tint"])
            foreground = LAColor.parse(json["foreground"])
        }

        public static let empty = Theme([:])
    }

    public let regions: [Region: LANode]
    public let theme: Theme
    public let deepLink: URL?

    public init(regions: [Region: LANode], theme: Theme = .empty, deepLink: URL? = nil) {
        self.regions = regions
        self.theme = theme
        self.deepLink = deepLink
    }

    public func node(_ region: Region) -> LANode? { regions[region] }

    /// Decodes the JSON string carried in the ActivityKit content state.
    ///
    /// Returns an empty layout on malformed input; a Live Activity that draws
    /// nothing is a much better failure than one that crashes the extension.
    public static func decode(_ json: String) -> LALayout {
        guard let data = json.data(using: .utf8),
              let root = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
        else {
            return LALayout(regions: [:])
        }

        var regions: [Region: LANode] = [:]
        if let rawRegions = root["regions"] as? [String: Any] {
            for (key, value) in rawRegions {
                guard let region = Region(rawValue: key),
                      let node = LANode.parse(value) else { continue }
                regions[region] = node
            }
        }

        let theme = (root["theme"] as? [String: Any]).map(Theme.init) ?? .empty
        let deepLink = (root["deepLink"] as? String).flatMap(URL.init(string:))
        return LALayout(regions: regions, theme: theme, deepLink: deepLink)
    }
}
