// Generated by `dart run live_activity_kit:setup` — do not edit.
// Source: package:live_activity_kit/ios/Shared/LAStyle.swift

import Foundation
import SwiftUI

/// Style primitives, mirroring `lib/src/components/style.dart`.

// MARK: - Color

public enum LAColor {

    /// Parses `#RGB`, `#RRGGBB` or `#RRGGBBAA`.
    ///
    /// Returns `nil` for anything unparseable so the renderer can fall back to
    /// the inherited foreground rather than painting an activity black.
    public static func parse(_ raw: Any?) -> Color? {
        guard var string = raw as? String else { return nil }
        if string.hasPrefix("#") { string.removeFirst() }

        if string.count == 3 {
            string = string.map { "\($0)\($0)" }.joined()
        }
        if string.count == 6 { string += "FF" }
        guard string.count == 8, let value = UInt64(string, radix: 16) else {
            return nil
        }

        let r = Double((value & 0xFF00_0000) >> 24) / 255
        let g = Double((value & 0x00FF_0000) >> 16) / 255
        let b = Double((value & 0x0000_FF00) >> 8) / 255
        let a = Double(value & 0x0000_00FF) / 255
        return Color(.sRGB, red: r, green: g, blue: b, opacity: a)
    }

    public static func parseAll(_ raw: Any?) -> [Color]? {
        guard let list = raw as? [Any] else { return nil }
        let colors = list.compactMap { parse($0) }
        return colors.count >= 2 ? colors : nil
    }
}

// MARK: - Font

public enum LAFontWeight {
    public static func parse(_ raw: Any?) -> Font.Weight? {
        switch raw as? String {
        case "ultraLight": return .ultraLight
        case "thin": return .thin
        case "light": return .light
        case "regular": return .regular
        case "medium": return .medium
        case "semibold": return .semibold
        case "bold": return .bold
        case "heavy": return .heavy
        case "black": return .black
        default: return nil
        }
    }
}

// MARK: - Alignment

public enum LAAlign: String {
    case start, center, end, baseline

    public static func parse(_ raw: Any?, default fallback: LAAlign) -> LAAlign {
        guard let name = raw as? String, let value = LAAlign(rawValue: name) else {
            return fallback
        }
        return value
    }

    /// Cross-axis alignment for a `VStack`.
    public var horizontal: HorizontalAlignment {
        switch self {
        case .start: return .leading
        case .center, .baseline: return .center
        case .end: return .trailing
        }
    }

    /// Cross-axis alignment for an `HStack`.
    public var vertical: VerticalAlignment {
        switch self {
        case .start: return .top
        case .center: return .center
        case .end: return .bottom
        case .baseline: return .firstTextBaseline
        }
    }

    public var frame: Alignment {
        switch self {
        case .start: return .leading
        case .center, .baseline: return .center
        case .end: return .trailing
        }
    }

    public var textAlignment: TextAlignment {
        switch self {
        case .start: return .leading
        case .center, .baseline: return .center
        case .end: return .trailing
        }
    }
}

public enum LADistribution: String {
    case start, center, end, spaceBetween, spaceAround

    public static func parse(_ raw: Any?) -> LADistribution {
        guard let name = raw as? String,
              let value = LADistribution(rawValue: name) else { return .start }
        return value
    }

    /// SwiftUI stacks have no main-axis distribution, so the renderer emulates
    /// it with leading/trailing/interleaved spacers.
    public var leadingSpacer: Bool {
        self == .center || self == .end || self == .spaceAround
    }

    public var trailingSpacer: Bool {
        self == .center || self == .start || self == .spaceAround
            || self == .spaceBetween
    }

    public var interleavedSpacers: Bool {
        self == .spaceBetween || self == .spaceAround
    }
}

// MARK: - Text alignment

public enum LATextAlign {
    public static func parse(_ raw: Any?) -> (TextAlignment, Alignment)? {
        switch raw as? String {
        case "leading": return (.leading, .leading)
        case "center": return (.center, .center)
        case "trailing": return (.trailing, .trailing)
        default: return nil
        }
    }
}

// MARK: - Insets

public struct LAInsets {
    public var top: CGFloat
    public var left: CGFloat
    public var bottom: CGFloat
    public var right: CGFloat

    public init(top: CGFloat = 0, left: CGFloat = 0, bottom: CGFloat = 0, right: CGFloat = 0) {
        self.top = top
        self.left = left
        self.bottom = bottom
        self.right = right
    }

    /// Accepts either a scalar (uniform) or `[top, left, bottom, right]`.
    public static func parse(_ raw: Any?) -> LAInsets? {
        if let value = raw as? Double {
            let v = CGFloat(value)
            return LAInsets(top: v, left: v, bottom: v, right: v)
        }
        guard let list = raw as? [Any], list.count == 4 else { return nil }
        let values = list.map { CGFloat(($0 as? Double) ?? 0) }
        return LAInsets(top: values[0], left: values[1], bottom: values[2], right: values[3])
    }

    public var edgeInsets: EdgeInsets {
        EdgeInsets(top: top, leading: left, bottom: bottom, trailing: right)
    }
}
