import SwiftUI
import WidgetKit

/// Entry point of the widget extension.
///
/// Generated by `dart run live_activity_kit:setup`. Safe to edit — the setup
/// command never overwrites a file you have modified unless you pass `--force`.
/// Add your own Home Screen widgets to the bundle alongside the Live Activity.
@main
struct LiveActivityKitWidgetBundle: WidgetBundle {
    var body: some Widget {
        if #available(iOS 16.1, *) {
            LiveActivityKitLiveActivity()
        }
    }
}
