// Generated by `dart run live_activity_kit:setup` — do not edit.
// Source: package:live_activity_kit/ios/Shared/LiveActivityKitAttributes.swift

import Foundation

#if canImport(ActivityKit)
import ActivityKit

/// The single, generic attributes type used by every activity this package
/// starts.
///
/// IMPORTANT: this file is compiled into **two** modules — the plugin (app
/// target) and the widget extension. ActivityKit matches activities to widget
/// configurations by the *unqualified type name*, so two identical copies in
/// separate modules interoperate correctly. `dart run live_activity_kit:setup`
/// keeps the extension's copy in sync; do not edit one without the other.
@available(iOS 16.1, *)
public struct LiveActivityKitAttributes: ActivityAttributes {

    /// Everything that can change while the activity is on screen.
    ///
    /// The UI travels as a JSON string rather than a nested `Codable` tree:
    /// ActivityKit caps the content state at 4 KiB, and a single string avoids
    /// paying for Swift's key metadata on every node. It also lets the Dart
    /// side own the schema — adding a component type never requires a change
    /// to this struct.
    public struct ContentState: Codable, Hashable {
        /// Serialized `LiveActivityLayout` — `{"regions": {...}, "theme": ...}`.
        public var payload: String

        /// Monotonic counter. ActivityKit drops an update whose content state
        /// is `==` the current one; the revision guarantees no-op-looking
        /// updates (a re-render with an unchanged tree) still land.
        public var revision: Int

        /// Schema version, so a widget extension built against an older
        /// package can detect a payload it cannot draw.
        public var version: Int

        public init(payload: String, revision: Int, version: Int = LiveActivityKitAttributes.schemaVersion) {
            self.payload = payload
            self.revision = revision
            self.version = version
        }
    }

    /// The caller-supplied id (`LiveActivity.show(id:)`). Static for the
    /// lifetime of the activity.
    public var id: String

    public init(id: String) {
        self.id = id
    }

    /// Bump when the JSON schema gains a breaking change.
    public static let schemaVersion = 1
}

#endif
